name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # take code from src folder from code.py file and pass it to open ai api and test there 
      - name : Test the code by passing it to open ai API 
 
      # if this test case passes then commit the code back to the code.py file 
      - name: OpenAI
        uses: riccardolinares/openai-commit@v0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-prompt: "Test this code : \n${{ github.event.head_commit.message }}"
        id: openai
      # if code fail then pass the message with the error 
      - name : if error encounter then show accordingly

      
