name : Pyhthon Package

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master]  # Trigger on commits to the 'master' branch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ChatGPT code reviewer
    steps:
      - name: ChatGPT as a reviewer
        uses: sychus/chatgpt-github-actions@1.7.1
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_engine: "gpt-3.5-turbo" #optional
          openai_temperature: 0.2 #optional
          openai_max_tokens: 2048 #optional
          mode: file # file or patch
          openai_prompt: "Review the code changes in this pull request and provide feedback on potential issues, best practices, and any suggestions for improvement."  
    
